miniERPmobile/Controllers/odbiorcaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using miniERPmobile.Models;

namespace miniERPmobile.Controllers
{
    public class odbiorcaController : Controller
    {
        private w59018Entities db = new w59018Entities();

        // GET: odbiorca
        public ActionResult Index()
        {
            return View(db.odbiorca.ToList());
        }

        // GET: odbiorca/Details/5
        public ActionResult Details(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            odbiorca odbiorca = db.odbiorca.Find(id);
            if (odbiorca == null)
            {
                return HttpNotFound();
            }
            return View(odbiorca);
        }

        // GET: odbiorca/Create
        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "odbiorca_id,nazwa,powiat,gmina,kodpoczt,miasto,poczta,ulica,nrdomu,rabat")] odbiorca odbiorca)
        {
            if (ModelState.IsValid)
            {
                db.odbiorca.Add(odbiorca);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(odbiorca);
        }

        // GET: odbiorca/Edit/5
        public ActionResult Edit(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            odbiorca odbiorca = db.odbiorca.Find(id);
            if (odbiorca == null)
            {
                return HttpNotFound();
            }
            return View(odbiorca);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "odbiorca_id,nazwa,powiat,gmina,kodpoczt,miasto,poczta,ulica,nrdomu,rabat")] odbiorca odbiorca)
        {
            odbiorca.rabat = Convert.ToDecimal(odbiorca.rabat);

            if (ModelState.IsValid)
            {
                db.Entry(odbiorca).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(odbiorca);
        }


        public ActionResult Delete(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            odbiorca odbiorca = db.odbiorca.Find(id);
            if (odbiorca == null)
            {
                return HttpNotFound();
            }
            return View(odbiorca);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(decimal id)
        {
            odbiorca odbiorca = db.odbiorca.Find(id);
            db.odbiorca.Remove(odbiorca);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

miniERPmobile/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>miniERP - wersja mobilna</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Strona główna", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
				@Html.ActionLink("Lista odbiorców", "Index", "odbiorca", new { area = "" }, new { @class = "navbar-brand" })
				@Html.ActionLink("Dodaj nowego odbiorcę", "Create", "odbiorca", new { area = "" }, new { @class = "navbar-brand" })
				
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>miniERPmobile 2019</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>